on:
  repository_dispatch:
    types: [update-blog-feed]
  workflow_dispatch:
permissions:
  contents: write
jobs:
  readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: sarisia/actions-readme-feed@v1
        id: feed
        with:
          url: 'https://kyohsuke.github.io/misc_notes/index.xml'
          file: 'README.md'
          format: '- ${year}-${02month}-${02day} [${title}](${url}?utm_source=github&utm_medium=profile)'
      - if: ${{ steps.feed.outputs.changed == 1 }}
        uses: sarisia/actions-commit@master
        with:
          name: "github-actions[bot]"
          email: "41898282+github-actions[bot]@users.noreply.github.com"
