on:
  push:
    branches:
      - master
  schedule:
    - cron:  '0 20 * * *'
jobs:
  readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: sarisia/actions-readme-feed@v1
        id: feed
        with:
          url: 'https://kyohsuke.github.io/misc_notes/index.xml'
          file: 'README.md'
          format: '- ${year}-${02month}-${02day} [${title}](${url})'
      - if: ${{ steps.feed.outputs.changed == 1 }}
        uses: sarisia/actions-commit@master
        with:
          name: "github-actions[bot]"
          email: "41898282+github-actions[bot]@users.noreply.github.com"
