on:
  push:
    branches:
      - master
  schedule:
    - cron:  '0 20 * * *'
jobs:
  readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: sarisia/actions-readme-feed@v1
        with:
          url: |
            https://kyohsuke.github.io/misc_notes/index.xml
          file: 'README.md'
          max_entry: 10
      - if: ${{ steps.feed.outputs.changed == true }}
        uses: sarisia/actions-commit@master
